# Generated by Django 3.2.11 on 2022-01-23 21:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('blog', '0002_cvindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateTimeField(verbose_name='Post date')),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('category', models.CharField(choices=[('News', 'News Post'), ('Data', 'Data Story'), ('Opinion', 'Opinion'), ('Fact', 'Fact check')], default='Blog', max_length=7)),
                ('topic', models.CharField(max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
