# Generated by Django 3.2.11 on 2022-01-24 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cvpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvpage',
            name='finish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Finish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvpage',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cvpage',
            name='category',
            field=models.CharField(choices=[('Experience', 'Experience'), ('Education', 'Education'), ('Portafolio', 'Portafolio')], default='Blog', max_length=10),
        ),
    ]
