# Generated by Django 3.2.11 on 2022-05-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_educationindexpage_experienceindexpage_portafolioindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvpage',
            name='category',
            field=models.CharField(choices=[('Experience', 'Experience'), ('Education', 'Education'), ('Portafolio', 'Portafolio'), ('About me', 'About me')], default='Blog', max_length=10),
        ),
    ]
