# Generated by Django 3.0.3 on 2020-03-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200316_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='category',
            field=models.CharField(choices=[('Blog', 'Blog Post'), ('Story', 'Data Story'), ('Opinion', 'Opinion'), ('Fact', 'Fact check')], default='Blog', max_length=7),
        ),
    ]
