# Generated by Django 3.0.3 on 2020-03-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='topic',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
