# Generated by Django 3.0.3 on 2020-04-04 09:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('blog', '0010_newsindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='category',
            field=models.CharField(choices=[('News', 'News Post'), ('Data', 'Data Story'), ('Opinion', 'Opinion'), ('Fact', 'Fact check')], default='Blog', max_length=7),
        ),
    ]
